### ISSUE TITLE
你可以测试一下性能

### ISSUE THREAD

**Issue by qianlihu8906** [NingShenTian/CsharpJson#1]
解析步骤清晰，点赞
可以参考miloyip的[性能测试方法](https://github.com/miloyip/nativejson-benchmark)。miloyip是这方面的世界级大神。
可以用里面的例子测试一下 [canada.json](https://raw.githubusercontent.com/mloskot/json_benchmark/master/data/canada.json ) 和 [citm_catalog.json](https://raw.githubusercontent.com/RichardHightower/json-parsers-benchmark/master/data/citm_catalog.json)

**Comment by NingShenTian** [comment]
嗯，好的。我这个都是递归解的，估计跑的不快。



发自我的小米手机
在 qianlihu <notifications@github.com>，2017年6月28日 上午10:10写道：

解析步骤清晰，点赞
可以参考miloyip的性能测试方法<https://github.com/miloyip/nativejson-benchmark>。miloyip是这方面的世界级大神。
可以用里面的例子测试一下 canada.json<https://raw.githubusercontent.com/mloskot/json_benchmark/master/data/canada.json> 和 citm_catalog.json<https://raw.githubusercontent.com/RichardHightower/json-parsers-benchmark/master/data/citm_catalog.json>

**Comment by NingShenTian** [comment]
https://raw.githubusercontent.com/mloskot/json_benchmark/master/data/canada.json 这个我这样解析：
`            using (StreamReader sr = File.OpenText("json.txt"))
            {
                string s = "";
                while ((s = sr.ReadLine()) != null)
                {
                    Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss fff"));
                    JsonDocument d = JsonDocument.FromString(s);
                    JsonObject o = d.Object;
                    Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss fff"));
                }
            }
`
![default](https://user-images.githubusercontent.com/14068570/27618772-cb067d6c-5bf0-11e7-8e63-caff44ef20b7.png)
不知道这个json解析速度多少比较合理。图片中是我的运行时间。我PC配置是i3处理器4G内存。

**Comment by NingShenTian** [comment]
![default](https://user-images.githubusercontent.com/14068570/27618797-f3cab2ea-5bf0-11e7-90a1-a27166a43168.png)
大约在200毫秒和300毫秒之间。

**Comment by NingShenTian** [comment]
效率低可能是递归的问题，尤其这种大文件，递归这么多层效率低下是肯定的。后面有时间，打算改成非递归的。

**Comment by qianlihu8906** [comment]
你可以看看[这个](https://github.com/miloyip/nativejson-benchmark)，下面有图，不过他的测试机型是i7的机器。
可以和qt的json解析作比较啊，如果性能和qt在一个数量级，就很好了，就完全不用改了

**Comment by NingShenTian** [comment]
其实，当我发现能解析没报错的时候，我就震惊了。原本预期是，拿别人的测试例子运行可能解不出来，咔，蹦溃了。



发自我的小米手机
在 qianlihu <notifications@github.com>，2017年6月28日 下午2:39写道：

你可以看看这个<https://github.com/miloyip/nativejson-benchmark>，下面有图，不过他的测试机型是i7的机器。
可以和qt的json解析作比较啊，如果性能和qt在一个数量级，就很好了，就完全不用改了

**Comment by qianlihu8906** [comment]
just close it
